#!/usr/bin/env sh
set -eu
exec 2>&1
#source /env

COMMAND=/usr/sbin/nginx
PID_FILE=/run/nginx.pid

# Create pid file's directory
install -d -o www-data -g www-data ${PID_FILE%/*}

# Check nginx command is executable or not
test -x ${COMMAND} || exit 0

# Test nginx configuration
${COMMAND} -t -q || exit 0

#trap "pkill -SIGHUP runsvdir" SIGTERM SIGINT

echo "Starting '${COMMAND}' with PID: $$"

exec ${COMMAND} -g "daemon off;error_log /dev/stdout info;"
