#!/usr/bin/env sh
set -eu
exec 2>&1
#source /env

if [ "$WEBSERVER" = "nginx" ]; then
  COMMAND=/usr/sbin/nginx
  PID_FILE=/run/nginx.pid

  # Create pid file's directory
  install -d -o nginx -g nginx ${PID_FILE%/*}

  # Check nginx command is executable or not
  test -x ${COMMAND} || exit 0

  # Test nginx configuration
  ${COMMAND} -t -q || exit 0

  #trap "pkill -SIGHUP runsvdir" SIGTERM SIGINT

  echo "Starting '${COMMAND}' with PID: $$"

  exec ${COMMAND} -g "daemon off;"
 else
  echo "--> INFO: disabling nginx service because: WEBSERVER=$WEBSERVER"
  sv down nginx
fi








