#!/usr/bin/env sh
set -eu
exec 2>&1
#source /env

NGINX_CONFWATCH=${NGINX_CONFWATCH:-/etc/nginx/conf.d}
COMMAND=/usr/local/sbin/nginx-confwatch
PID_FILE=/run/nginx-confwatch.pid

# Create pid file's directory
install -d -o www-data -g www-data ${PID_FILE%/*}

# Check nginx command is executable or not
test -x ${COMMAND} || exit 0

# Test nginx configuration
#${COMMAND} -t -q || exit 0

#trap "pkill -SIGHUP runsvdir" SIGTERM SIGINT

echo "Starting '${COMMAND}' with PID: $$"

echo $$ > $PID_FILE

exec ${COMMAND} "$NGINX_CONFWATCH"
